# PyTorch Lesson 1

Today, I will be using the `torch` library in Python to teach myself the aspects of deep learning and the many scenarios that deep learning can be applied to. This file will be dedicated to tensor operation in `torch`. Tensors are arrays or matrices that can be added, subtracted and multiplied either by element wise multiplicaton or matrix multiplication.

Here are some examples of what you can do with tensors. 

In [2]:
# importing torch
import torch

In [3]:
my_list = [[1,2,3], [4,5,6]]

# converting to a tensor
my_tensor = torch.tensor(my_list)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
# Shape and Data Type
print(my_tensor.shape)  # prints the shape of the tensor
print(my_tensor.dtype)  # prints the data type of the tensor
print(my_tensor.device)  # prints the device of the tensor (CPU or GPU)

torch.Size([2, 3])
torch.int64
cpu


In [7]:
# second tensor
my_tensor_2 = torch.tensor([[7,8,9], [10,11,12]])
print(my_tensor_2)

# Adding the tensors
added_tensor = my_tensor + my_tensor_2
print(added_tensor)

# Subtracting the tensors
subtracted_tensor = my_tensor - my_tensor_2
print(subtracted_tensor)

# Multiplying the tensors
multiplied_tensor = my_tensor * my_tensor_2
print(multiplied_tensor)

# Dividing the tensors
divided_tensor = my_tensor / my_tensor_2
print(divided_tensor)

# Matrix multiplication (using transpose for proper dimensions)
matrix_multiplied_tensor = my_tensor @ my_tensor_2.t()
print(matrix_multiplied_tensor)

tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[ 50,  68],
        [122, 167]])
